using System.Text.Json;

namespace CedarSharp;

/// <summary>The authorization decision returned by Cedar.</summary>
public enum CedarDecision
{
    /// <summary>The request is denied.</summary>
    Deny,
    /// <summary>The request is allowed. Inspect policy errors separately.</summary>
    Allow
}

/// <summary>Source offsets are UTF-8 byte offsets, with an exclusive end.</summary>
/// <param name="Label">Optional label for the source range.</param>
/// <param name="Start">Inclusive UTF-8 byte offset.</param>
/// <param name="End">Exclusive UTF-8 byte offset.</param>
public sealed record CedarSourceLocation(string? Label, long Start, long End);

/// <summary>Complete structured upstream diagnostic, including related diagnostics and source ranges.</summary>
public sealed class CedarDiagnostic
{
    /// <summary>Human-readable upstream diagnostic message.</summary>
    public string Message { get; }
    /// <summary>Optional guidance for resolving the diagnostic.</summary>
    public string? Help { get; }
    /// <summary>Optional upstream diagnostic code.</summary>
    public string? Code { get; }
    /// <summary>Optional URL for more information about the diagnostic.</summary>
    public string? Url { get; }
    /// <summary>Optional upstream severity, such as error, warning, or advice.</summary>
    public string? Severity { get; }
    /// <summary>Source ranges, measured in UTF-8 bytes.</summary>
    public IReadOnlyList<CedarSourceLocation> SourceLocations { get; }
    /// <summary>Related upstream diagnostics.</summary>
    public IReadOnlyList<CedarDiagnostic> Related { get; }
    /// <summary>A copied, unmodified upstream JSON value.</summary>
    public JsonElement Raw { get; }
    internal CedarDiagnostic(JsonElement e)
    {
        Raw = e.Clone(); Message = JsonWire.String(e, "message");
        Help = e.GetProperty("help").GetString(); Code = e.GetProperty("code").GetString();
        Url = e.GetProperty("url").GetString(); Severity = e.GetProperty("severity").GetString();
        SourceLocations = JsonWire.Array(e, "sourceLocations", x => new CedarSourceLocation(
            x.GetProperty("label").GetString(), x.GetProperty("start").GetInt64(), x.GetProperty("end").GetInt64()));
        Related = JsonWire.Array(e, "related", x => new CedarDiagnostic(x));
    }
}

/// <summary>A diagnostic associated with a specific Cedar policy ID.</summary>
/// <param name="PolicyId">ID supplied by the policy set or generated by Cedar.</param>
/// <param name="Error">Complete upstream diagnostic.</param>
public sealed record CedarPolicyDiagnostic(string PolicyId, CedarDiagnostic Error)
{
    internal static CedarPolicyDiagnostic Read(JsonElement e) => new(JsonWire.String(e, "policyId"), new(e.GetProperty("error")));
}

/// <summary>A completed Cedar call. A parsing failure has no decision; an Allow may still have policy errors.</summary>
public sealed class CedarAuthorizationResult
{
    /// <summary>Whether Cedar evaluated the request; an Allow can still have policy errors.</summary>
    public bool IsSuccess { get; }
    /// <summary>Cedar decision, or null if the request could not be parsed or evaluated.</summary>
    public CedarDecision? Decision { get; }
    /// <summary>IDs of policies that determined the decision; upstream ordering is not guaranteed.</summary>
    public IReadOnlyList<string> DeterminingPolicies { get; } = System.Array.Empty<string>();
    /// <summary>Policy evaluation errors. These may be present even when the decision is Allow.</summary>
    public IReadOnlyList<CedarPolicyDiagnostic> PolicyErrors { get; } = System.Array.Empty<CedarPolicyDiagnostic>();
    /// <summary>Errors that prevented a completed operation.</summary>
    public IReadOnlyList<CedarDiagnostic> Errors { get; } = System.Array.Empty<CedarDiagnostic>();
    /// <summary>Upstream warnings outside policy evaluation.</summary>
    public IReadOnlyList<CedarDiagnostic> Warnings { get; }
    /// <summary>A copied, unmodified upstream JSON value.</summary>
    public JsonElement Raw { get; }
    internal CedarAuthorizationResult(JsonElement e)
    {
        Raw = e.Clone(); IsSuccess = JsonWire.Success(e);
        Warnings = JsonWire.Array(e, "warnings", x => new CedarDiagnostic(x));
        if (!IsSuccess) { Errors = JsonWire.Array(e, "errors", x => new CedarDiagnostic(x)); return; }
        var response = e.GetProperty("response");
        Decision = JsonWire.String(response, "decision") switch
        {
            "allow" => CedarDecision.Allow, "deny" => CedarDecision.Deny,
            _ => throw new JsonException("Unknown Cedar decision.")
        };
        var diagnostics = response.GetProperty("diagnostics");
        DeterminingPolicies = JsonWire.Array(diagnostics, "reason", x => x.GetString() ?? throw new JsonException("Null policy ID."));
        PolicyErrors = JsonWire.Array(diagnostics, "errors", CedarPolicyDiagnostic.Read);
    }
}

/// <summary>Separates a failed parse from a completed validation that found invalid policies.</summary>
public sealed class CedarValidationResult
{
    /// <summary>Whether policies and schema parsed so validation could run; use IsValid for the outcome.</summary>
    public bool IsSuccess { get; }
    /// <summary>Whether strict validation completed without validation errors.</summary>
    public bool IsValid => IsSuccess && ValidationErrors.Count == 0;
    /// <summary>Schema-based policy validation errors.</summary>
    public IReadOnlyList<CedarPolicyDiagnostic> ValidationErrors { get; } = System.Array.Empty<CedarPolicyDiagnostic>();
    /// <summary>Schema-based policy validation warnings.</summary>
    public IReadOnlyList<CedarPolicyDiagnostic> ValidationWarnings { get; } = System.Array.Empty<CedarPolicyDiagnostic>();
    /// <summary>Errors that prevented a completed operation.</summary>
    public IReadOnlyList<CedarDiagnostic> Errors { get; } = System.Array.Empty<CedarDiagnostic>();
    /// <summary>Upstream warnings outside policy evaluation.</summary>
    public IReadOnlyList<CedarDiagnostic> Warnings { get; }
    /// <summary>A copied, unmodified upstream JSON value.</summary>
    public JsonElement Raw { get; }
    internal CedarValidationResult(JsonElement e)
    {
        Raw = e.Clone(); IsSuccess = JsonWire.Success(e);
        Warnings = JsonWire.Array(e, IsSuccess ? "otherWarnings" : "warnings", x => new CedarDiagnostic(x));
        if (!IsSuccess) { Errors = JsonWire.Array(e, "errors", x => new CedarDiagnostic(x)); return; }
        ValidationErrors = JsonWire.Array(e, "validationErrors", CedarPolicyDiagnostic.Read);
        ValidationWarnings = JsonWire.Array(e, "validationWarnings", CedarPolicyDiagnostic.Read);
    }
}

/// <summary>The result of a Cedar parsing or data-validation check.</summary>
public sealed class CedarCheckResult
{
    /// <summary>Whether the input parsed and passed this check.</summary>
    public bool IsSuccess { get; }
    /// <summary>Errors that prevented the check from passing.</summary>
    public IReadOnlyList<CedarDiagnostic> Errors { get; }
    /// <summary>A copied, unmodified upstream JSON value.</summary>
    public JsonElement Raw { get; }
    internal CedarCheckResult(JsonElement e)
    {
        Raw = e.Clone(); IsSuccess = JsonWire.Success(e);
        Errors = IsSuccess ? System.Array.Empty<CedarDiagnostic>() : JsonWire.Array(e, "errors", x => new CedarDiagnostic(x));
    }
}

/// <summary>Identity reported by the loaded bridge, together with its verified asset path and hash.</summary>
/// <param name="AbiVersion">Version of the native C ABI.</param>
/// <param name="SdkVersion">Version of the loaded Cedar engine.</param>
/// <param name="LanguageVersion">Cedar policy language version.</param>
/// <param name="BridgeVersion">Version of the CedarSharp native bridge.</param>
/// <param name="RustVersion">Rust compiler version used to build the bridge.</param>
/// <param name="Target">Native compilation target triple.</param>
/// <param name="Features">Enabled Cedar extension features.</param>
/// <param name="NativePath">Absolute path of the loaded native library.</param>
/// <param name="Sha256">SHA-256 hash of the loaded native library.</param>
public sealed record CedarVersion(uint AbiVersion, string SdkVersion, string LanguageVersion, string BridgeVersion,
    string RustVersion, string Target, IReadOnlyList<string> Features, string NativePath, string Sha256);

/// <summary>A native loading, ABI, transport, or result-decoding failure. Never represents a Cedar Deny.</summary>
public sealed class CedarBridgeException : Exception
{
    /// <summary>Native boundary status, when one was returned.</summary>
    public uint? Status { get; }
    /// <summary>Creates a native bridge failure with an optional status and underlying cause.</summary>
    public CedarBridgeException(string message, uint? status = null, Exception? innerException = null) : base(message, innerException) => Status = status;
}

/// <summary>A Cedar JSON call envelope was rejected before evaluation. It is a caller input error, not a Cedar Deny.</summary>
public sealed class CedarInputException : ArgumentException
{
    /// <summary>Creates a Cedar JSON call-envelope input error.</summary>
    public CedarInputException(string message, Exception? innerException = null) : base(message, innerException) { }
}
